brokers: 'exchange-kafka.dingir-exchange:9092'
grpc_addr: '127.0.0.1:50061' # TODO: Update for staging
db: postgres://postgres:postgres_AA9944@rollup-state-manager-pq.rollup-state-manager/rollup_state_manager
