brokers: 'exchange-kafka.dingir-exchange:9092'
prover_cluster_db: postgres://coordinator:coordinator_AA9944@prover-cluster-pq.prover-cluster/prover_cluster
rollup_state_manager_db: postgres://postgres:postgres_AA9944@rollup-state-manager-pq.rollup-state-manager/rollup_state_manager
