name: CI

on:
  push:
    branches:
      - master
      - prod
      - release/*
  pull_request:
    branches:
      - master
      - prod
      - release/*

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.51.0

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Cache cargo
        uses: actions/cache@v2
        with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install 1.51.0 toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.51.0
          override: true
          components: rustfmt, clippy
      
      - name: Run "cargo fmt & check"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      
      - name: Run "cargo clippy"
        uses: actions-rs/cargo@v1
        # continue-on-error: true
        with:
          command: clippy
          args: -- -D warnings
